export const teams = [
  {
    position: 1,
    name: "Manchester City",
    win: 28,
    draw: 5,
    lost: 5,
    goalDifference: "94:33",
    points: 89,
  },
  {
    position: 2,
    name: "Arsenal",
    win: 26,
    draw: 6,
    lost: 6,
    goalDifference: "88:43",
    points: 84,
  },
  {
    position: 3,
    name: "Manchester Utd",
    win: 23,
    draw: 6,
    lost: 9,
    goalDifference: "58:43",
    points: 75,
  },
  {
    position: 4,
    name: "Newcastle",
    win: 19,
    draw: 14,
    lost: 5,
    goalDifference: "68:33",
    points: 71,
  },
  {
    position: 5,
    name: "Liverpool",
    win: 19,
    draw: 10,
    lost: 9,
    goalDifference: "75:47",
    points: 67,
  },
  {
    position: 6,
    name: "Brighton",
    win: 18,
    draw: 8,
    lost: 12,
    goalDifference: "72:53",
    points: 62,
  },
  {
    position: 7,
    name: "Aston Villa",
    win: 18,
    draw: 7,
    lost: 13,
    goalDifference: "51:46",
    points: 61,
  },
  {
    position: 8,
    name: "Tottenham",
    win: 18,
    draw: 6,
    lost: 14,
    goalDifference: "70:63",
    points: 60,
  },
  {
    position: 9,
    name: "Brentford",
    win: 15,
    draw: 14,
    lost: 9,
    goalDifference: "58:46",
    points: 59,
  },
  {
    position: 10,
    name: "Fulham",
    win: 15,
    draw: 7,
    lost: 16,
    goalDifference: "55:53",
    points: 52,
  },
  {
    position: 11,
    name: "Crystal Palace",
    win: 11,
    draw: 12,
    lost: 15,
    goalDifference: "40:49",
    points: 45,
  },
  {
    position: 12,
    name: "Chelsea",
    win: 11,
    draw: 11,
    lost: 16,
    goalDifference: "38:47",
    points: 44,
  },
  {
    position: 13,
    name: "Wolves",
    win: 11,
    draw: 8,
    lost: 19,
    goalDifference: "31:58",
    points: 41,
  },
  {
    position: 14,
    name: "West Ham",
    win: 11,
    draw: 7,
    lost: 20,
    goalDifference: "42:55",
    points: 40,
  },
  {
    position: 15,
    name: "Bournemouth",
    win: 11,
    draw: 6,
    lost: 21,
    goalDifference: "37:71",
    points: 39,
  },
  {
    position: 16,
    name: "Nottingham",
    win: 9,
    draw: 11,
    lost: 18,
    goalDifference: "38:68",
    points: 38,
  },
  {
    position: 17,
    name: "Everton",
    win: 8,
    draw: 12,
    lost: 18,
    goalDifference: "34:57",
    points: 36,
  },
  {
    position: 18,
    name: "Leicester",
    win: 9,
    draw: 7,
    lost: 22,
    goalDifference: "51:68",
    points: 34,
  },
  {
    position: 19,
    name: "Leeds",
    win: 7,
    draw: 10,
    lost: 21,
    goalDifference: "48:78",
    points: 31,
  },
  {
    position: 20,
    name: "Southampton",
    win: 6,
    draw: 7,
    lost: 25,
    goalDifference: "36:73",
    points: 25,
  },
];
